compiler/natives/src/testing: Override frameSkip to avoid runtime.Callers.
frameSkip relies on runtime.Callers when testing.T.Helper was called.

Fixes:

	$ gopherjs test --run=TestBuilder strings
	--- FAIL: TestBuilder (0.07s)

	github.com/gopherjs/gopherjs/test.481734121:1412
	          throw new Error(msg);
	                ^
	Error: testing: zero callers found