compiler/natives/src/math: Slightly increase tolerances in tests to fix TestGamma.
Before this change, TestGamma fails with:

	$ gopherjs test --short --minify --run='^Test' math
	--- FAIL: TestGamma (0.08s)
		all_test.go:2234: Gamma(171) = 7.257415615307958e+306, want 7.257415615307999e+306
		all_test.go:2234: Gamma(171.6) = 1.5858969096672286e+308, want 1.5858969096672565e+308
		all_test.go:2234: Gamma(171.624) = 1.794211759924792e+308, want 1.7942117599248104e+308
		all_test.go:2234: Gamma(-171.5) = 1.93162654317124e-310, want 1.9316265431712e-310
	FAIL
	FAIL	math	0.786s

The tolerances are defined with these values upstream in Go 1.8:

	func close(a, b float64) bool      { return tolerance(a, b, 1e-14) }
	func veryclose(a, b float64) bool  { return tolerance(a, b, 4e-16) }