compiler/natives/src/io: Skip TestMultiWriterSingleChainFlatten.
TestMultiWriterSingleChainFlatten was added in Go 1.10, and it needs to
be skipped (just like TestMultiReaderFlatten) because it relies on
unsupported runtime features.

Related to golang/go@060d1a57401180bc003c0d882033b35ca19374a2.

Fixes:

	=== RUN   TestMultiWriterSingleChainFlatten
	--- FAIL: TestMultiWriterSingleChainFlatten (0.01s)
	    test.558082205:38: multiWriter did not flatten chained multiWriters: expected writeDepth 12, got 4
	FAIL    io  0.888s