compiler: Set anonymous bit for struct fields correctly.
In Go 1.9, specifically commit golang/go@9bbb07ddec63e5e747f1cd9dbf82b7504b29dd09,
reflect.structField.offset was changed to offsetAnon.
The first bit of offsetAnon represents isAnonymous.
Previously, the name being blank was the test for anonymous,
but now it's that bit.

This change makes it so we set that bit correctly, and
always set the name. This keeps things consistent with Go 1.9
and the changes to reflect package, and fixes failing tests.

Skip TestStructOfFieldName because it uses the unimplemented
reflect.StructOf.

Fixes:

	$ gopherjs test --short --run=Field reflect
	--- FAIL: TestAnonymousFields (0.00s)
		all_test.go:2104: no field 'int'
	--- FAIL: TestFieldByIndex (0.00s)
		test.092084297:36534: S1.S0 not found
		test.092084297:36534: S2.S1 not found
	--- FAIL: TestFieldByName (0.00s)
		test.092084297:36648: S1.A not found
		test.092084297:36688: S1.A value not found
		test.092084297:36648: S1.S0 not found
		test.092084297:36648: S1.C not found
		test.092084297:36688: S1.C value not found
		test.092084297:36648: S2.S1 not found
		test.092084297:36648: S2.B not found
		test.092084297:36688: S2.B value not found
		test.092084297:36648: S2.C not found
		test.092084297:36688: S2.C value not found
		test.092084297:36648: S3.A not found
		test.092084297:36688: S3.A value not found
		test.092084297:36648: S5.Y not found
		test.092084297:36648: S10.Y not found
	--- FAIL: TestFieldPkgPath (0.00s)
		all_test.go:2379: testStruct: Field([2]).Anonymous = false, want true
	--- FAIL: TestStructOfFieldName (0.00s)

	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/test.092084297:1412
	          throw new Error(msg);
	                ^
	Error: runtime error: native function not implemented: reflect.addReflectOff
	    ...
	FAIL	reflect	0.825s