compiler/natives/src/reflect: Set pkgPath for new implements checks.
In Go 1.9, specifically commit golang/go@2ddc3e940e180d3466a364f224b3e54a1749d827,
reflect.implements was modified to look at pkgPath in more cases.

Previously, GopherJS didn't always set pkgPath in some places. This
caused panics and failures in TestImplements and TestAssignableTo.

This change fixes that, allowing all reflect tests to pass.

Fixes:

	$ go install -tags=gopherjsdev -v && touch $(which gopherjs) && gopherjs test --short reflect
	--- FAIL: TestImplements (0.00s)

	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/gopherjs/gopherjs/test.903476986:1412
	          throw new Error(msg);
	                ^
	Error: runtime error: invalid memory address or nil pointer dereference
	    ...
	FAIL	reflect	4.658s