compiler/natives/src/sync: Implement newly referenced test helpers.
This is for golang/go@3ea53cb08f1709b2f9bf39cfcfaa1d285256baa2. It adds
new test helpers, which are referenced by TestPoolNew. Implement them
as no-ops. This should be fine, since we don't need to worry about about
goroutines migrating (I think).

Fixes the following error:

	=== RUN   TestPoolNew
	--- FAIL: TestPoolNew (0.00s)
	/home/ubuntu/gopherjs/test.823209923:1480
	        throw err;
	        ^

	Error: runtime error: native function not implemented: sync.runtime_procPin
	    at $callDeferred (/home/ubuntu/gopherjs/test.823209923:1412:17)
	    at $panic (/home/ubuntu/gopherjs/test.823209923:1451:3)
	    at $b (/home/ubuntu/gopherjs/test.823209923:29945:5)
	    at $callDeferred (/home/ubuntu/gopherjs/test.823209923:1424:23)
	    at $panic (/home/ubuntu/gopherjs/test.823209923:1451:3)
	    at $packages.runtime.throw$1 (/home/ubuntu/gopherjs/test.823209923:2557:3)
	    at Object.$packages.sync.runtime_procPin [as Runtime_procPin] (/home/ubuntu/gopherjs/test.823209923:3831:3)
	    at $packages.sync_test.TestPoolNew (/home/ubuntu/gopherjs/test.823209923:33929:15)
	    at $packages.testing.tRunner (/home/ubuntu/gopherjs/test.823209923:29982:8)
	    at $goroutine (/home/ubuntu/gopherjs/test.823209923:1471:19)
	    at $runScheduled (/home/ubuntu/gopherjs/test.823209923:1511:7)
	    at $schedule (/home/ubuntu/gopherjs/test.823209923:1527:5)
	    at $go (/home/ubuntu/gopherjs/test.823209923:1503:3)
	    at Object.<anonymous> (/home/ubuntu/gopherjs/test.823209923:41471:1)
	    at Object.<anonymous> (/home/ubuntu/gopherjs/test.823209923:41474:4)
	    at Module._compile (module.js:541:32)
	    at Object.Module._extensions..js (module.js:550:10)
	    at Module.load (module.js:458:32)
	    at tryModuleLoad (module.js:417:12)
	    at Function.Module._load (module.js:409:3)
	    at Module.runMain (module.js:575:10)
	    at run (node.js:348:7)
	    at startup (node.js:140:9)
	    at node.js:463:3
	FAIL	sync	1.805s